<template>                       
<!-- meteorology-ranges card -->
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-background-cic">
                <h4 class="text-white">Rangos recomendados para Temperatura y Humedad relativa</h4>
            </div>
            <div class="card-body">
                <div class="row">

                    <div class="col-sm-6 col-lg-3">
                        <div class="card text-white bg-gradient-info">
                            <div class="card-body">
                                <div class="text-value-lg">30 %</div>
                                <div>Humedad relativa</div>
                                <div class="text-value-lg">20.28-24.16 C°</div>
                                <div>Temperatura Invierno</div>
                                <div class="text-value-lg">23.33-26.66 C°</div>
                                <div>Temperatura Verano</div>
                            </div>                                                    
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-3">
                        <div class="card text-white bg-gradient-info">
                            <div class="card-body">
                                <div class="text-value-lg">40 %</div>
                                <div>Humedad relativa</div>
                                <div class="text-value-lg">20.00-23.88 C°</div>
                                <div>Temperatura Invierno</div>
                                <div class="text-value-lg">23.05-26.66 C°</div>
                                <div>Temperatura Verano</div>
                            </div>                                                    
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-3">
                        <div class="card text-white bg-gradient-info">
                            <div class="card-body">
                                <div class="text-value-lg">50 %</div>
                                <div>Humedad relativa</div>
                                <div class="text-value-lg">20.00-23.61 C°</div>
                                <div>Temperatura Invierno</div>
                                <div class="text-value-lg">22.77-26.11 C°</div>
                                <div>Temperatura Verano</div>
                            </div>                                                    
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-3">
                        <div class="card text-white bg-gradient-info">
                            <div class="card-body">
                                <div class="text-value-lg">60 %</div>
                                <div>Humedad relativa</div>
                                <div class="text-value-lg">19.72-23.33 C°</div>
                                <div>Temperatura Invierno</div>
                                <div class="text-value-lg">22.77-25.83 C°</div>
                                <div>Temperatura Verano</div>
                            </div>                                                    
                        </div>
                    </div>

                    
                </div>

            </div>
        </div>
    </div>
</div>
<!-- meteorology-ranges CARD-->
</template>
<script>
    export default {
      data() {
        return { 
        }
      },
      methods: {
      },
      mounted() {
          
      }
    }
</script>